columns:

  - name: Category
    type: string
    missing:
      strategy: fill_value
      value: "Unknown"

  - name: Item
    type: string
    missing:
      strategy: fill_value
      value: "Unknown"

  - name: Price Per Unit
    type: float
    missing:
      strategy: derive
      derive_from:
        - Total Spent
        - Quantity
      fallback:
        strategy: median_by_category
        group_col: Category

  - name: Quantity
    type: integer
    missing:
      strategy: derive
      derive_from:
        - Total Spent
        - Price Per Unit
      fallback:
        strategy: median_by_category
        group_col: Category

  - name: Total Spent
    type: float
    missing:
      strategy: derive
      derive_from:
        - Price Per Unit
        - Quantity
      fallback:
        strategy: median_by_category
        group_col: Category

  - name: Payment Method
    type: string
    missing:
      strategy: fill_value
      value: "Unknown"

  - name: Location
    type: string
    missing:
      strategy: fill_value
      value: "Unknown"

  - name: Transaction Date
    type: datetime
    missing:
      strategy: fill_value
      value: NULL

  - name: Discount Applied
    type: boolean
    missing:
      strategy: fill_value
      value: false


outliers:

  - column: Price Per Unit
    method: iqr
    factor: 1.5

  - column: Quantity
    method: iqr
    factor: 1.5
    id_column: Transaction ID

  - column: Total Spent
    method: iqr
    factor: 1.5
    id_column: Transaction ID


validations:

  - column: Price Per Unit
    type: non_negative

  - column: Total Spent
    type: non_negative

  - column: Discount Applied
    type: boolean_values

  - column: Transaction Date
    type: date_format
    format: '%Y-%m-%d'

  - column: Transaction Date
    type: not_future

  - column: Payment Method
    type: allowed_values
    values:
      - Cash
      - Credit Card
      - Digital Wallet

  - column: Category
    type: allowed_values
    values:
      - Beverages
      - Butchers
      - Computers and electric accessories
      - Electric household essentials
      - Food
      - Furniture
      - Milk Products
      - Patisserie

  - column: Location
    type: allowed_values
    values:
      - In-store
      - Online